brew "asdf"
brew "gh"
brew "git"
brew "gpg"
brew "hub"
brew "shellcheck"
brew "tree"

cask "1password"
cask "bartender"
cask "bluesnooze"
cask "docker"
cask "dropbox"
# don't fail if Chrome is already installed
cask "google-chrome" unless File.exist?('/Applications/Google Chrome.app')
cask "google-drive"
cask "firefox"
cask "iterm2"
cask "signal"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
