- hosts: localhost
  tasks:
    - name: Symlink dotfiles
      file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: ~/.{{ item }}
        state: link
      with_items:
        - ackrc
        - asdfrc
        - editorconfig
        - gemrc
        - gitconfig
        - gitconfig-mac
        - gitconfig-work
        - gitignore
        - irbrc
        - pryrc
        - rdebugrc
        - sqliterc
        - tmux.conf
        - vimrc
        - zshrc
    - name: Clone git-plugins
      git:
        repo: https://github.com/afeld/git-plugins.git
        dest: ~/dev/git-plugins
    - name: Add VSCode settings
      file:
        src: "{{ playbook_dir }}/vscode/settings.json"
        dest: ~/Library/Application Support/Code/User/settings.json
        state: link
        force: true
