- hosts: localhost
  connection: local
  gather_facts: false
  handlers:
    - name: Restart Dock
      ansible.builtin.command: killall Dock
    - name: Restart SystemUIServer
      ansible.builtin.command: killall SystemUIServer
  tasks:
    - name: Set up dotfiles
      import_tasks: tasks/dotfiles.yml

    - name: Set up Git
      import_tasks: tasks/git.yml

    - name: Set up oh-my-zsh
      import_tasks: tasks/oh_my_zsh.yml

    - name: Set up asdf
      import_tasks: tasks/asdf.yml

    - name: Set up macOS
      import_tasks: tasks/macos.yml
