- hosts: localhost
  handlers:
    - name: Restart Dock
      command: killall Dock
  tasks:
    - name: Symlink dotfiles
      file:
        src: "{{ playbook_dir }}/dotfiles/{{ item }}"
        dest: ~/.{{ item }}
        state: link
        force: true
      with_items:
        - ackrc
        - asdfrc
        - gemrc
        - gitconfig
        - gitconfig-mac
        - gitconfig-work
        - gitignore
        - irbrc
        - pryrc
        - rdebugrc
        - sqliterc
        - tmux.conf
        - vimrc
        - zshrc

    - name: Set up Git
      import_tasks: tasks/git.yml

    - name: Set up oh-my-zsh
      import_tasks: tasks/oh_my_zsh.yml

    - name: Set up Visual Studio Code
      import_tasks: tasks/vscode.yml

    - name: Set up asdf
      import_tasks: tasks/asdf.yml

    - name: Auto-hide the Dock
      command: defaults write com.apple.dock autohide -int 1
      notify: Restart Dock
