- hosts: localhost
  tasks:
    - name: Symlink dotfiles
      file:
        src: "{{ playbook_dir }}/{{ item }}"
        dest: ~/.{{ item }}
        state: link
      with_items:
        - ackrc
        - asdfrc
        - gemrc
        - gitconfig
        - gitconfig-mac
        - gitconfig-work
        - gitignore
        - irbrc
        - pryrc
        - rdebugrc
        - sqliterc
        - tmux.conf
        - vimrc
        - zshrc
    - name: Set up Git
      import_tasks: tasks/git.yml
    - name: Set up oh-my-zsh
      import_tasks: tasks/oh_my_zsh.yml
    - name: Set up Visual Studio Code
      import_tasks: tasks/vscode.yml
