- hosts: localhost
  handlers:
    - name: Restart Dock
      command: killall Dock
  tasks:
    - name: Set up dotfiles
      import_tasks: tasks/dotfiles.yml

    - name: Set up Git
      import_tasks: tasks/git.yml

    - name: Set up oh-my-zsh
      import_tasks: tasks/oh_my_zsh.yml

    - name: Set up asdf
      import_tasks: tasks/asdf.yml

    - name: Set up macOS
      import_tasks: tasks/macos.yml
