- name: Get installed asdf plugins
  command: asdf plugin list
  changed_when: false
  # given an error when there are none
  ignore_errors: true
  register: asdf_plugins

- name: Install asdf plugins
  command: asdf plugin add {{ item }}
  when: item not in asdf_plugins.stdout
  loop:
    - nodejs
    - python
    - ruby
    - terraform
