- name: Get installed asdf plugins
  ansible.builtin.command: asdf plugin list
  changed_when: false
  # avoid failing when there are no plugins installed yet
  failed_when: false
  register: asdf_plugins

- name: Install asdf plugins
  ansible.builtin.command: asdf plugin add {{ item }}
  when: item not in (asdf_plugins.stdout_lines | default([]))
  loop:
    - nodejs
    - python
    - ruby
    - terraform
