- name: List dotfiles
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/dotfiles"
    hidden: true
  register: dotfiles

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/.{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ dotfiles.files | sort(attribute='path') }}"
