- name: Clone git-plugins
  git:
    repo: https://github.com/afeld/git-plugins.git
    dest: ~/dev/git-plugins

# https://github.com/afeld/git-setup
- name: Set up Git
  shell: curl -fsSL https://raw.githubusercontent.com/afeld/git-setup/master/setup.sh | sh

# https://github.com/18F/laptop#want-to-install-just-git-seekret
- name: Set up Git Seekret
  shell: curl -s https://raw.githubusercontent.com/18F/laptop/master/seekrets-install | bash -
