- name: Install oh-my-zsh
  # https://ohmyz.sh/#install
  ansible.builtin.shell: |
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
