- name: Add VSCode settings
  file:
    src: "{{ playbook_dir }}/vscode/settings.json"
    dest: ~/Library/Application Support/Code/User/settings.json
    state: link
    force: true

- name: Get installed VSCode extensions
  command: code --list-extensions
  changed_when: false
  register: extensions

- name: Install VSCode extensions
  command: code --install-extension {{ item }}
  when: item not in extensions.stdout
  loop:
    - esbenp.prettier-vscode
    - sdras.night-owl
